name: Generate example swatches

on:
  push:
    branches: [main]
    paths:
      - examples/colors.css
      - color-swatches.mjs
      - action.yml

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          files: 'examples/colors.css'
          out-dir: 'examples/swatches'
