name: Generate example swatches

on:
  push:
    branches: [main]
    paths:
      - README.md
      - color-swatches.mjs
      - action.yml

  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          files: 'README.md'
          out-dir: 'swatches'
